### ISSUE TITLE
Typo on priority list

### ISSUE THREAD

**Issue by nethalo** [Percona-Lab/proxysql-scheduler#3]
Where it says 
`--priority=--priority=10.0.0.22:3306,10.0.0.23:3306,10.0.0.33:3306`

Should be
`--priority=10.0.0.22:3306,10.0.0.23:3306,10.0.0.33:3306`

**Comment by nethalo** [comment]
@Tusamarco

**Comment by Tusamarco** [comment]
fix in QA branch
